### ISSUE TITLE
Support autofac 4.0.0-rc2-240

### ISSUE THREAD

**Issue by alberto-riggi** [thepirat000/AutoFactory#1]
Version 4.0.0-rc2-240 of Autofac has been released (https://github.com/autofac/Autofac/releases). Is it possible to create a Autofactory rc2 version with the autofac rc2 dependency instead to integrate gracefully with netcore RC2?

Regards

**Comment by thepirat000** [comment]
Will work on that very soon. Thanks!

**Comment by thepirat000** [comment]
Implemented on [Automatic Factory 5.0.3-pre](https://www.nuget.org/packages/AutoFactory/5.0.3-pre).
Closing this.
